name: .NET API POI

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: true
        default: 'N/A'
  push:
    branches: [ main ]
    paths:
      - 'apis/poi/**'
  pull_request:
    branches: [ main ]
    paths:    
      - 'apis/poi/**'
      - '.github/workflows/dotnet.yml'
env:
  ACR_URL: 'openhackxqzxmauhbxtiiacr.azurecr.io'
  
jobs:
  build:

    runs-on: ubuntu-latest  
    
    steps:
        - uses: actions/checkout@v2
        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 2.1.x   
            
        - name: Restore dependencies
          run: dotnet restore apis/poi/poi.sln
      
        - name: Build
          run: dotnet build --no-restore apis/poi/poi.sln    
